### ISSUE TITLE
Windows app won't start

### ISSUE THREAD

**Issue by naked-head** [ModBros/mobro-raspberrypi#12] opened 2023-01-08 16:46 UTC
I had used your app many times but now it's chrashing without any alert. Looking on my windows registry event I found this error any time I had tried to launch the app, with administrator privilege too

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 - <System>
  <Provider Name="Microsoft-Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" /> 
  <EventID Qualifiers="0">10016</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2023-01-08T16:32:23.6520686Z" /> 
  <EventRecordID>58437</EventRecordID> 
  <Correlation ActivityID="{de2044de-9ea8-4140-961e-7b2abdeabb30}" /> 
  <Execution ProcessID="1396" ThreadID="31240" /> 
  <Channel>System</Channel> 
  <Computer>MyPC</Computer> 
  <Security UserID="S-1-5-21-131938479-3630242823-3704963213-1001" /> 
  </System>
-<EventData>
  <Data Name="param1">application specific settings</Data> 
  <Data Name="param2">Local</Data> 
  <Data Name="param3">Activation</Data> 
  <Data Name="param4">{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}</Data> 
  <Data Name="param5">{15C20B67-12E7-4BB6-92BB-7AFF07997402}</Data> 
  <Data Name="param6">MyPC</Data> 
  <Data Name="param7">giorg</Data> 
  <Data Name="param8">S-1-5-21-131938479-3630242823-3704963213-1001</Data> 
  <Data Name="param9">LocalHost (LRPC)</Data> 
  <Data Name="param10">Unavailable</Data> 
  <Data Name="param11">Unavailable</Data> 
  </EventData>
  </Event>
```

I don't know what else I can find to help you track the error because I don't receive any messages from the app.
I hope you can help me
thanks

**Comment by daves-weblab** [comment] 2023-01-09 10:34
Hey, this can happen when the app breaks while writing a settings file. Another user had a similar issue here [https://www.mod-bros.com/en/forum/t/desktop-running-but-not-running~1234](https://www.mod-bros.com/en/forum/t/desktop-running-but-not-running~1234). Usually it's the channels.json in the MoBro_Local directory as described in the forum topic. I'll close the issue with that since this is the repository of the raspberry image and the issue is about the windows app. If you have any further questions please use our forum :) Thanks and cheers!

**Closed as completed by daves-weblab** 2023-01-09 10:34 UTC
